README.md:Add partner information
bnb-chain/bas-template-bsc pull request #2
Opened 2022-09-19 02:55 UTC by xuan-cu

### Description

add a description of your changes here...

### Rationale

tell us why we need these changes...

### Example

add an example CLI or API response...

### Changes

Notable changes: 
* add each change in a bullet point here
* ...

2022-09-19 12:16 UTC, realuncle approved these changes

2022-09-21 08:46 UTC, guagualvcha approved these changes

2022-09-21 08:49 UTC, xuan-io approved these changes

2022-09-21 08:59 UTC, guagualvcha requested changes
Please refine the PR description

2022-09-21 09:24 UTC, merged